language: r
cache: packages
cran: http://cran.rstudio.com
dist: bionic

os:
  - linux
  - osx
  
r:
  - oldrel
  - release
  - devel

jobs:
  exclude:
  - r: devel
    os: osx
   
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then tlmgr install elsarticle cancel; sudo apt install ghostscript; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo tlmgr install elsarticle cancel multirow; brew install ghostscript; fi
   
script:
  - R CMD build .
  - R CMD check *.tar.gz --as-cran
