language: r
sudo: true
cache: packages
cran: http://cran.rstudio.com

os:
  - linux

r:
  - oldrel
  - release
  - devel

before_install:
  - tlmgr install elsarticle cancel
   
script:
  - R CMD build .
  - R CMD check *.tar.gz --as-cran
